"""Main sensor type definitions for the EG4 Web Monitor integration.

This module contains the SENSOR_TYPES dictionary which defines all sensor
configurations for inverter entities.
"""

from __future__ import annotations

from homeassistant.const import (
    EntityCategory,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
)

# Sensor types and their units
SENSOR_TYPES = {
    # Power sensors
    "ac_power": {
        "name": "AC Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power",
    },
    "dc_power": {
        "name": "DC Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power",
    },
    "load_power": {
        "name": "Load Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    # Total output power (split-phase systems)
    "output_power": {
        "name": "Output Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "consumption_power": {
        "name": "Consumption Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "grid_power": {
        "name": "Grid Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
    },
    "grid_import_power": {
        "name": "Grid Import Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower-import",
    },
    "grid_export_power": {
        "name": "Grid Export Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower-export",
    },
    "battery_power": {
        "name": "Battery Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "hybrid_power": {
        "name": "Hybrid Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant-outline",
    },
    "power_output": {
        "name": "Power Output",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:flash",
    },
    "rectifier_power": {
        "name": "Rectifier Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:flash-triangle",
    },
    "ac_couple_power": {
        "name": "AC Couple Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "eps_power": {
        "name": "EPS Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
    },
    "eps_power_l1": {
        "name": "EPS Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
    },
    "eps_power_l2": {
        "name": "EPS Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
    },
    # EPS per-leg apparent power (split-phase, regs 131-132)
    "eps_apparent_power_l1": {
        "name": "EPS Apparent Power L1",
        "unit": "VA",
        "device_class": "apparent_power",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
    },
    "eps_apparent_power_l2": {
        "name": "EPS Apparent Power L2",
        "unit": "VA",
        "device_class": "apparent_power",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
    },
    # EPS per-leg energy (split-phase, regs 133-138)
    "eps_energy_today_l1": {
        "name": "EPS Energy Today L1",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:power-plug",
    },
    "eps_energy_today_l2": {
        "name": "EPS Energy Today L2",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:power-plug",
    },
    "eps_energy_total_l1": {
        "name": "EPS Energy Total L1",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:power-plug",
    },
    "eps_energy_total_l2": {
        "name": "EPS Energy Total L2",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:power-plug",
    },
    # US split-phase per-leg power (regs 195-204)
    "inverter_power_l1": {
        "name": "Inverter Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power",
    },
    "inverter_power_l2": {
        "name": "Inverter Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power",
    },
    "rectifier_power_l1": {
        "name": "Rectifier Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:flash-triangle",
    },
    "rectifier_power_l2": {
        "name": "Rectifier Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:flash-triangle",
    },
    "grid_export_power_l1": {
        "name": "Grid Export Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower-export",
    },
    "grid_export_power_l2": {
        "name": "Grid Export Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower-export",
    },
    "grid_import_power_l1": {
        "name": "Grid Import Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower-import",
    },
    "grid_import_power_l2": {
        "name": "Grid Import Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower-import",
    },
    "generator_voltage_l1": {
        "name": "Generator Voltage L1",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
    },
    "generator_voltage_l2": {
        "name": "Generator Voltage L2",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:engine",
        "suggested_display_precision": 1,
    },
    # Synthetic sensor: Total Load Power (EPS + Consumption for power flow charts)
    "total_load_power": {
        "name": "Total Load Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "battery_status": {
        "name": "Battery Status",
        "icon": "mdi:battery-heart",
    },
    # Voltage sensors
    "ac_voltage": {
        "name": "AC Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:flash",
        "suggested_display_precision": 1,
    },
    "dc_voltage": {
        "name": "DC Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:flash",
    },
    "battery_voltage": {
        "name": "Battery Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "bus1_voltage": {
        "name": "Bus 1 Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:sine-wave",
        "suggested_display_precision": 1,
    },
    "bus2_voltage": {
        "name": "Bus 2 Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:sine-wave",
        "suggested_display_precision": 1,
    },
    # Grid voltage and frequency sensors (R/S/T phases)
    "grid_voltage_r": {
        "name": "Grid Voltage R",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
    },
    "grid_voltage": {
        "name": "Grid Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
    },
    "grid_voltage_s": {
        "name": "Grid Voltage S",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
    },
    "grid_voltage_t": {
        "name": "Grid Voltage T",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 1,
    },
    "grid_frequency": {
        "name": "Grid Frequency",
        "unit": UnitOfFrequency.HERTZ,
        "device_class": "frequency",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
        "suggested_display_precision": 2,
    },
    # EPS (Emergency Power Supply) voltage sensors
    "eps_voltage_r": {
        "name": "EPS Voltage R",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
    },
    "eps_voltage": {
        "name": "EPS Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
    },
    "eps_voltage_s": {
        "name": "EPS Voltage S",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
    },
    "eps_voltage_t": {
        "name": "EPS Voltage T",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
    },
    # Split-phase EPS voltages (L1/L2 ~120V each)
    "eps_voltage_l1": {
        "name": "EPS Voltage L1",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
    },
    "eps_voltage_l2": {
        "name": "EPS Voltage L2",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
        "suggested_display_precision": 1,
    },
    "eps_frequency": {
        "name": "EPS Frequency",
        "unit": UnitOfFrequency.HERTZ,
        "device_class": "frequency",
        "state_class": "measurement",
        "icon": "mdi:power-plug",
        "suggested_display_precision": 2,
    },
    # Current sensors
    "ac_current": {
        "name": "AC Current",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:current-ac",
    },
    "dc_current": {
        "name": "DC Current",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:current-dc",
    },
    "battery_current": {
        "name": "Battery Current",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    # Energy sensors
    "total_energy": {
        "name": "Total Energy",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:lightning-bolt",
    },
    "daily_energy": {
        "name": "Daily Energy",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:calendar-today",
    },
    "monthly_energy": {
        "name": "Monthly Energy",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:calendar-month",
    },
    "yearly_energy": {
        "name": "Yearly Energy",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:calendar-year",
    },
    # Current day energy sensors (values need to be divided by 10)
    "yield": {
        "name": "Yield",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
    },
    "discharging": {
        "name": "Discharging",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-arrow-down",
    },
    "charging": {
        "name": "Charging",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-arrow-up",
    },
    "consumption": {
        "name": "Consumption",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:home-lightning-bolt",
    },
    "grid_export": {
        "name": "Grid Export",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-export",
    },
    "grid_import": {
        "name": "Grid Import",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-import",
    },
    # Lifetime energy sensors (values need to be divided by 10)
    "yield_lifetime": {
        "name": "Yield (Lifetime)",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
    },
    "discharging_lifetime": {
        "name": "Discharging (Lifetime)",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-arrow-down",
    },
    "charging_lifetime": {
        "name": "Charging (Lifetime)",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-arrow-up",
    },
    "consumption_lifetime": {
        "name": "Consumption (Lifetime)",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:home-lightning-bolt",
    },
    "grid_export_lifetime": {
        "name": "Grid Export (Lifetime)",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-export",
    },
    "grid_import_lifetime": {
        "name": "Grid Import (Lifetime)",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-import",
    },
    # Parallel Group aggregate battery sensors (calculated from all inverters)
    "parallel_battery_power": {
        "name": "Battery Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "parallel_battery_soc": {
        "name": "Battery State of Charge",
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "parallel_battery_max_capacity": {
        "name": "Battery Max Capacity",
        "unit": "Ah",
        "device_class": None,
        "state_class": "measurement",
        "icon": "mdi:battery-high",
    },
    "parallel_battery_current_capacity": {
        "name": "Battery Current Capacity",
        "unit": "Ah",
        "device_class": None,
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "parallel_battery_voltage": {
        "name": "Battery Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:flash",
    },
    "parallel_battery_current": {
        "name": "Battery Current",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:current-dc",
    },
    "parallel_battery_charge_rate": {
        "name": "Battery Charge Rate",
        "unit": "%/h",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
        "suggested_display_precision": 2,
    },
    "parallel_battery_count": {
        "name": "Battery Count",
        "unit": None,
        "device_class": None,
        "state_class": "measurement",
        "icon": "mdi:counter",
    },
    # Battery charge/discharge energy sensors (pylxpweb 0.3.3+)
    "battery_charge": {
        "name": "Battery Charge",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-charging",
    },
    "battery_discharge": {
        "name": "Battery Discharge",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-minus",
    },
    "battery_charge_lifetime": {
        "name": "Battery Charge (Lifetime)",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-charging",
    },
    "battery_discharge_lifetime": {
        "name": "Battery Discharge (Lifetime)",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-minus",
    },
    # Frequency
    "frequency": {
        "name": "Frequency",
        "unit": UnitOfFrequency.HERTZ,
        "device_class": "frequency",
        "state_class": "measurement",
        "icon": "mdi:sine-wave",
    },
    # Temperature
    "temperature": {
        "name": "Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer",
    },
    # Battery specific
    "state_of_charge": {
        "name": "State of Charge",
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "state_of_health": {
        "name": "State of Health",
        "unit": "%",
        "state_class": "measurement",
        "icon": "mdi:battery-heart",
    },
    "cycle_count": {
        "name": "Cycle Count",
        "state_class": "total_increasing",
        "icon": "mdi:counter",
    },
    # Battery Bank aggregate sensors (pylxpweb 0.3.3+)
    "battery_bank_voltage": {
        "name": "Battery Bank Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_bank_soc": {
        "name": "Battery Bank SOC",
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_bank_current": {
        "name": "Battery Bank Current",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_bank_charge_rate": {
        "name": "Battery Bank Charge Rate",
        "unit": "%/h",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
        "suggested_display_precision": 2,
    },
    "battery_bank_power": {
        "name": "Battery Bank Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
    },
    "battery_bank_max_capacity": {
        "name": "Battery Bank Max Capacity",
        "unit": "Ah",
        "state_class": "measurement",
        "icon": "mdi:battery-high",
    },
    "battery_bank_current_capacity": {
        "name": "Battery Bank Current Capacity",
        "unit": "Ah",
        "state_class": "measurement",
        "icon": "mdi:battery-medium",
    },
    "battery_bank_remain_capacity": {
        "name": "Battery Bank Remaining Capacity",
        "unit": "Ah",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_bank_full_capacity": {
        "name": "Battery Bank Full Capacity",
        "unit": "Ah",
        "state_class": "measurement",
        "icon": "mdi:battery-high",
    },
    "battery_bank_capacity_percent": {
        "name": "Battery Bank Capacity Percent",
        "unit": "%",
        "state_class": "measurement",
        "icon": "mdi:battery-heart",
    },
    "battery_bank_count": {
        "name": "Battery Count",
        "state_class": "measurement",
        "icon": "mdi:counter",
        "entity_category": "diagnostic",
    },
    "battery_bank_status": {
        "name": "Battery Bank Status",
        "icon": "mdi:information",
        "entity_category": "diagnostic",
    },
    # Cross-battery diagnostics (pylxpweb >= 0.6.7)
    "battery_bank_soc_delta": {
        "name": "Battery Bank SOC Delta",
        "unit": "%",
        "state_class": "measurement",
        "icon": "mdi:battery-sync",
        "entity_category": "diagnostic",
    },
    "battery_bank_min_soh": {
        "name": "Battery Bank Min SOH",
        "unit": "%",
        "state_class": "measurement",
        "icon": "mdi:battery-heart-variant",
        "entity_category": "diagnostic",
    },
    "battery_bank_soh_delta": {
        "name": "Battery Bank SOH Delta",
        "unit": "%",
        "state_class": "measurement",
        "icon": "mdi:battery-heart-variant",
        "entity_category": "diagnostic",
    },
    "battery_bank_voltage_delta": {
        "name": "Battery Bank Voltage Delta",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery-sync",
        "entity_category": "diagnostic",
    },
    "battery_bank_cell_voltage_delta_max": {
        "name": "Battery Bank Max Cell Voltage Delta",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery-alert",
        "entity_category": "diagnostic",
        "suggested_display_precision": 3,
    },
    "battery_bank_cycle_count": {
        "name": "Battery Bank Cycle Count",
        "state_class": "total_increasing",
        "icon": "mdi:counter",
        "entity_category": "diagnostic",
    },
    "battery_bank_cycle_count_delta": {
        "name": "Battery Bank Cycle Count Delta",
        "state_class": "measurement",
        "icon": "mdi:counter",
        "entity_category": "diagnostic",
    },
    "battery_bank_max_cell_temp": {
        "name": "Battery Bank Max Cell Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer-alert",
        "entity_category": "diagnostic",
    },
    "battery_bank_temp_delta": {
        "name": "Battery Bank Temperature Delta",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer-lines",
        "entity_category": "diagnostic",
    },
    "battery_bank_min_cell_voltage": {
        "name": "Battery Bank Min Cell Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery-minus-variant",
        "entity_category": "diagnostic",
        "suggested_display_precision": 3,
    },
    "battery_bank_min_cell_temp": {
        "name": "Battery Bank Min Cell Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer-low",
        "entity_category": "diagnostic",
    },
    "battery_bank_bms_charge_current_limit": {
        "name": "Battery Bank BMS Charge Current Limit",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:current-dc",
        "entity_category": "diagnostic",
    },
    "battery_bank_bms_discharge_current_limit": {
        "name": "Battery Bank BMS Discharge Current Limit",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:current-dc",
        "entity_category": "diagnostic",
    },
    "battery_bank_bms_charge_voltage_ref": {
        "name": "Battery Bank BMS Charge Voltage Reference",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:flash",
        "entity_category": "diagnostic",
    },
    "battery_bank_bms_discharge_cutoff": {
        "name": "Battery Bank BMS Discharge Cutoff Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:flash-off",
        "entity_category": "diagnostic",
    },
    "battery_bank_bms_battery_type": {
        "name": "Battery Bank Battery Type",
        "icon": "mdi:battery-unknown",
        "entity_category": "diagnostic",
    },
    "battery_bank_voltage_inv_sample": {
        "name": "Battery Bank Voltage (Inverter Sample)",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery",
        "entity_category": "diagnostic",
    },
    # Additional battery sensors from batteryArray
    "battery_real_voltage": {
        "name": "Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_real_current": {
        "name": "Current",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_real_power": {
        "name": "Real Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_cell_voltage_max": {
        "name": "Cell Voltage Max",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery-plus-variant",
    },
    "battery_cell_voltage_min": {
        "name": "Cell Voltage Min",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery-minus-variant",
    },
    "battery_cell_voltage_diff": {
        "name": "Cell Voltage Difference",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery-sync",
    },
    "battery_mos_temperature": {
        "name": "MOS Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer",
    },
    "battery_env_temperature": {
        "name": "Environment Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer",
    },
    "battery_cell_temp_max": {
        "name": "Max Cell Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer-chevron-up",
    },
    "battery_cell_temp_min": {
        "name": "Min Cell Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer-chevron-down",
    },
    "battery_ambient_temperature": {
        "name": "Ambient Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:home-thermometer",
    },
    "battery_remaining_capacity": {
        "name": "Remaining Capacity",
        "unit": "Ah",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_full_capacity": {
        "name": "Full Capacity",
        "unit": "Ah",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_design_capacity": {
        "name": "Design Capacity",
        "unit": "Ah",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_rsoc": {
        "name": "Relative SOC",
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_asoc": {
        "name": "Absolute SOC",
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "icon": "mdi:battery",
    },
    "battery_firmware_version": {
        "name": "Firmware Version",
        "icon": "mdi:chip",
        "entity_category": "diagnostic",
    },
    "battery_capacity_percentage": {
        "name": "Capacity Percentage",
        "unit": "%",
        "state_class": "measurement",
        "icon": "mdi:battery-charging-100",
    },
    "battery_max_charge_current": {
        "name": "Max Charge Current",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:current-dc",
    },
    "battery_charge_rate": {
        "name": "Charge Rate",
        "unit": "%/h",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
        "suggested_display_precision": 2,
    },
    "battery_max_cell_temp_num": {
        "name": "Max Temp Cell Number",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    "battery_min_cell_temp_num": {
        "name": "Min Temp Cell Number",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    "battery_max_cell_voltage_num": {
        "name": "Max Voltage Cell Number",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    "battery_min_cell_voltage_num": {
        "name": "Min Voltage Cell Number",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    "firmware_version": {
        "name": "Firmware Version",
        "icon": "mdi:chip",
        "entity_category": "diagnostic",
    },
    "inverter_family": {
        "name": "Inverter Family",
        "icon": "mdi:family-tree",
        "entity_category": "diagnostic",
    },
    "device_type_code": {
        "name": "Device Type Code",
        "icon": "mdi:identifier",
        "entity_category": "diagnostic",
    },
    "grid_type": {
        "name": "Grid Type",
        "icon": "mdi:transmission-tower",
        "entity_category": "diagnostic",
    },
    "battery_balance_status": {
        "name": "Balance Status",
        "icon": "mdi:scale-balance",
    },
    "battery_protection_status": {
        "name": "Protection Status",
        "icon": "mdi:shield-check",
    },
    "battery_fault_status": {
        "name": "Fault Status",
        "icon": "mdi:alert-circle",
    },
    "battery_warning_status": {
        "name": "Warning Status",
        "icon": "mdi:alert",
    },
    # Battery temperature sensors (pylxpweb 0.3.3+)
    "battery_max_cell_temp": {
        "name": "Max Cell Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer-high",
    },
    "battery_min_cell_temp": {
        "name": "Min Cell Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer-low",
    },
    # Battery cell voltage sensors (pylxpweb 0.3.3+)
    "battery_max_cell_voltage": {
        "name": "Max Cell Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery-plus",
    },
    "battery_min_cell_voltage": {
        "name": "Min Cell Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery-minus",
    },
    "battery_cell_voltage_delta": {
        "name": "Cell Voltage Delta",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:delta",
        "suggested_display_precision": 3,
    },
    "battery_cell_temp_delta": {
        "name": "Cell Temperature Delta",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:delta",
    },
    # Battery capacity sensors (pylxpweb 0.3.3+)
    "battery_discharge_capacity": {
        "name": "Discharge Capacity",
        "unit": "Ah",
        "icon": "mdi:battery-arrow-down",
        "entity_category": "diagnostic",
    },
    "battery_charge_voltage_ref": {
        "name": "Charge Voltage Reference",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
    },
    # Battery metadata sensors (pylxpweb 0.3.3+)
    "battery_serial_number": {
        "name": "Serial Number",
        "icon": "mdi:identifier",
        "entity_category": "diagnostic",
    },
    "battery_type": {
        "name": "Battery Type Code",
        "icon": "mdi:battery",
        "entity_category": "diagnostic",
    },
    "battery_type_text": {
        "name": "Battery Type",
        "icon": "mdi:battery-sync",
        "entity_category": "diagnostic",
    },
    "battery_bms_model": {
        "name": "BMS Model",
        "icon": "mdi:chip",
        "entity_category": "diagnostic",
    },
    "battery_index": {
        "name": "Index",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    # PV String sensors
    "pv1_voltage": {
        "name": "PV1 Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:solar-panel",
    },
    "pv2_voltage": {
        "name": "PV2 Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:solar-panel",
    },
    "pv3_voltage": {
        "name": "PV3 Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:solar-panel",
    },
    "pv1_power": {
        "name": "PV1 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-panel",
    },
    "pv2_power": {
        "name": "PV2 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-panel",
    },
    "pv3_power": {
        "name": "PV3 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-panel",
    },
    # GridBOSS MidBox specific sensors
    "grid_voltage_l1": {
        "name": "Grid Voltage L1",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
    },
    "grid_voltage_l2": {
        "name": "Grid Voltage L2",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
    },
    "grid_voltage_l3": {
        "name": "Grid Voltage L3",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
    },
    "grid_current_l1": {
        "name": "Grid Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
    },
    "grid_current_l2": {
        "name": "Grid Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
    },
    "grid_current_l3": {
        "name": "Grid Current L3",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
    },
    "load_voltage_l1": {
        "name": "Load Voltage L1",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "load_voltage_l2": {
        "name": "Load Voltage L2",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "load_voltage_l3": {
        "name": "Load Voltage L3",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "load_current_l1": {
        "name": "Load Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "load_current_l2": {
        "name": "Load Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "load_current_l3": {
        "name": "Load Current L3",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "load_power_l1": {
        "name": "Load Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "load_power_l2": {
        "name": "Load Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "load_power_l3": {
        "name": "Load Power L3",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:home-lightning-bolt",
    },
    "grid_power_l1": {
        "name": "Grid Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
    },
    "grid_power_l2": {
        "name": "Grid Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
    },
    "grid_power_l3": {
        "name": "Grid Power L3",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:transmission-tower",
    },
    "ups_voltage": {
        "name": "UPS Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
    },
    "ups_current": {
        "name": "UPS Current",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
    },
    "ups_current_l1": {
        "name": "UPS Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
    },
    "ups_current_l2": {
        "name": "UPS Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
    },
    "ups_power": {
        "name": "UPS Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
    },
    "ups_power_l1": {
        "name": "UPS Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
    },
    "ups_power_l2": {
        "name": "UPS Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:battery-charging",
    },
    # Status sensors (diagnostic)
    "status_code": {
        "name": "Status Code",
        "icon": "mdi:numeric",
        "entity_category": "diagnostic",
    },
    "status_text": {
        "name": "Status",
        "icon": "mdi:information",
        "entity_category": "diagnostic",
    },
    "has_data": {
        "name": "Has Runtime Data",
        "icon": "mdi:database-check",
        "entity_category": "diagnostic",
    },
    # New runtime sensors
    "pv_total_power": {
        "name": "PV Total Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power",
    },
    "internal_temperature": {
        "name": "Internal Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer",
        "entity_category": "diagnostic",
    },
    "radiator1_temperature": {
        "name": "Radiator 1 Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:radiator",
        "entity_category": "diagnostic",
    },
    "radiator2_temperature": {
        "name": "Radiator 2 Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:radiator",
        "entity_category": "diagnostic",
    },
    # BT Temperature Sensor (Modbus register 108, local-only)
    # "12K BT temperature" per LuxPower Modbus documentation
    "bt_temperature": {
        "name": "BT Temperature",
        "unit": UnitOfTemperature.CELSIUS,
        "device_class": "temperature",
        "state_class": "measurement",
        "icon": "mdi:thermometer",
        "entity_category": "diagnostic",
    },
    # GridBOSS Smart Load sensors
    "smart_load_power": {
        "name": "Smart Load Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load1_power": {
        "name": "Smart Load 1 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load2_power": {
        "name": "Smart Load 2 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load3_power": {
        "name": "Smart Load 3 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load4_power": {
        "name": "Smart Load 4 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    # GridBOSS Smart Port Status sensors
    "smart_port1_status": {
        "name": "Smart Port 1 Status",
        "icon": "mdi:electric-switch",
        "entity_category": "diagnostic",
        "device_class": "enum",
        "options": ["unused", "smart_load", "ac_couple"],
    },
    "smart_port2_status": {
        "name": "Smart Port 2 Status",
        "icon": "mdi:electric-switch",
        "entity_category": "diagnostic",
        "device_class": "enum",
        "options": ["unused", "smart_load", "ac_couple"],
    },
    "smart_port3_status": {
        "name": "Smart Port 3 Status",
        "icon": "mdi:electric-switch",
        "entity_category": "diagnostic",
        "device_class": "enum",
        "options": ["unused", "smart_load", "ac_couple"],
    },
    "smart_port4_status": {
        "name": "Smart Port 4 Status",
        "icon": "mdi:electric-switch",
        "entity_category": "diagnostic",
        "device_class": "enum",
        "options": ["unused", "smart_load", "ac_couple"],
    },
    # GridBOSS Aggregate Energy sensors (L1 + L2 combined)
    "ups_today": {
        "name": "UPS Energy Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-charging-100",
    },
    "ups_total": {
        "name": "UPS Energy Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:battery-charging-100",
    },
    "grid_export_today": {
        "name": "Grid Export Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-export",
    },
    "grid_export_total": {
        "name": "Grid Export Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-export",
    },
    "grid_import_today": {
        "name": "Grid Import Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-import",
    },
    "grid_import_total": {
        "name": "Grid Import Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:transmission-tower-import",
    },
    "load_today": {
        "name": "Load Energy Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:home-lightning-bolt",
    },
    "load_total": {
        "name": "Load Energy Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:home-lightning-bolt",
    },
    # GridBOSS AC Couple energy sensors
    "ac_couple1_today": {
        "name": "AC Couple 1 Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
    },
    "ac_couple1_total": {
        "name": "AC Couple 1 Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
    },
    "ac_couple2_today": {
        "name": "AC Couple 2 Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
    },
    "ac_couple2_total": {
        "name": "AC Couple 2 Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
    },
    "ac_couple3_today": {
        "name": "AC Couple 3 Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
    },
    "ac_couple3_total": {
        "name": "AC Couple 3 Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
    },
    "ac_couple4_today": {
        "name": "AC Couple 4 Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
    },
    "ac_couple4_total": {
        "name": "AC Couple 4 Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:solar-power",
    },
    # GridBOSS Smart Load aggregate energy sensors (L1 + L2 combined)
    "smart_load1_today": {
        "name": "Smart Load 1 Energy Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:electric-switch",
    },
    "smart_load1_total": {
        "name": "Smart Load 1 Energy Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:electric-switch",
    },
    "smart_load2_today": {
        "name": "Smart Load 2 Energy Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:electric-switch",
    },
    "smart_load2_total": {
        "name": "Smart Load 2 Energy Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:electric-switch",
    },
    "smart_load3_today": {
        "name": "Smart Load 3 Energy Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:electric-switch",
    },
    "smart_load3_total": {
        "name": "Smart Load 3 Energy Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:electric-switch",
    },
    "smart_load4_today": {
        "name": "Smart Load 4 Energy Today",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:electric-switch",
    },
    "smart_load4_total": {
        "name": "Smart Load 4 Energy Total",
        "unit": UnitOfEnergy.KILO_WATT_HOUR,
        "device_class": "energy",
        "state_class": "total_increasing",
        "icon": "mdi:electric-switch",
    },
    # GridBOSS Generator sensors
    "generator_voltage": {
        "name": "Generator Voltage",
        "unit": UnitOfElectricPotential.VOLT,
        "device_class": "voltage",
        "state_class": "measurement",
        "icon": "mdi:engine",
    },
    "generator_frequency": {
        "name": "Generator Frequency",
        "unit": UnitOfFrequency.HERTZ,
        "device_class": "frequency",
        "state_class": "measurement",
        "icon": "mdi:engine",
    },
    "generator_power": {
        "name": "Generator Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:engine",
    },
    # GridBOSS Phase Lock Frequency
    "phase_lock_frequency": {
        "name": "Phase Lock Frequency",
        "unit": UnitOfFrequency.HERTZ,
        "device_class": "frequency",
        "state_class": "measurement",
        "icon": "mdi:sine-wave",
    },
    # GridBOSS Generator L1/L2 sensors
    "generator_current_l1": {
        "name": "Generator Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:engine",
    },
    "generator_current_l2": {
        "name": "Generator Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:engine",
    },
    "generator_power_l1": {
        "name": "Generator Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:engine",
    },
    "generator_power_l2": {
        "name": "Generator Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:engine",
    },
    # GridBOSS Smart Load L1/L2 Power sensors
    "smart_load1_power_l1": {
        "name": "Smart Load 1 Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load1_power_l2": {
        "name": "Smart Load 1 Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load2_power_l1": {
        "name": "Smart Load 2 Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load2_power_l2": {
        "name": "Smart Load 2 Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load3_power_l1": {
        "name": "Smart Load 3 Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load3_power_l2": {
        "name": "Smart Load 3 Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load4_power_l1": {
        "name": "Smart Load 4 Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    "smart_load4_power_l2": {
        "name": "Smart Load 4 Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
    },
    # GridBOSS AC Couple aggregate Power sensors (per-port totals)
    "ac_couple1_power": {
        "name": "AC Couple 1 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "ac_couple2_power": {
        "name": "AC Couple 2 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "ac_couple3_power": {
        "name": "AC Couple 3 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "ac_couple4_power": {
        "name": "AC Couple 4 Power",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    # GridBOSS AC Couple L1/L2 Power sensors
    "ac_couple1_power_l1": {
        "name": "AC Couple 1 Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "ac_couple1_power_l2": {
        "name": "AC Couple 1 Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "ac_couple2_power_l1": {
        "name": "AC Couple 2 Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "ac_couple2_power_l2": {
        "name": "AC Couple 2 Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "ac_couple3_power_l1": {
        "name": "AC Couple 3 Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "ac_couple3_power_l2": {
        "name": "AC Couple 3 Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "ac_couple4_power_l1": {
        "name": "AC Couple 4 Power L1",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    "ac_couple4_power_l2": {
        "name": "AC Couple 4 Power L2",
        "unit": UnitOfPower.WATT,
        "device_class": "power",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
    },
    # GridBOSS Smart Port Current sensors (per-port L1/L2, Modbus regs 18-25)
    # Dynamically created based on port status (same as power/energy sensors).
    "smart_load1_current_l1": {
        "name": "Smart Load 1 Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
        "suggested_display_precision": 1,
    },
    "smart_load1_current_l2": {
        "name": "Smart Load 1 Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
        "suggested_display_precision": 1,
    },
    "smart_load2_current_l1": {
        "name": "Smart Load 2 Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
        "suggested_display_precision": 1,
    },
    "smart_load2_current_l2": {
        "name": "Smart Load 2 Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
        "suggested_display_precision": 1,
    },
    "smart_load3_current_l1": {
        "name": "Smart Load 3 Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
        "suggested_display_precision": 1,
    },
    "smart_load3_current_l2": {
        "name": "Smart Load 3 Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
        "suggested_display_precision": 1,
    },
    "smart_load4_current_l1": {
        "name": "Smart Load 4 Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
        "suggested_display_precision": 1,
    },
    "smart_load4_current_l2": {
        "name": "Smart Load 4 Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:electric-switch",
        "suggested_display_precision": 1,
    },
    "ac_couple1_current_l1": {
        "name": "AC Couple 1 Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
    },
    "ac_couple1_current_l2": {
        "name": "AC Couple 1 Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
    },
    "ac_couple2_current_l1": {
        "name": "AC Couple 2 Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
    },
    "ac_couple2_current_l2": {
        "name": "AC Couple 2 Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
    },
    "ac_couple3_current_l1": {
        "name": "AC Couple 3 Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
    },
    "ac_couple3_current_l2": {
        "name": "AC Couple 3 Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
    },
    "ac_couple4_current_l1": {
        "name": "AC Couple 4 Current L1",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
    },
    "ac_couple4_current_l2": {
        "name": "AC Couple 4 Current L2",
        "unit": UnitOfElectricCurrent.AMPERE,
        "device_class": "current",
        "state_class": "measurement",
        "icon": "mdi:solar-power-variant",
        "suggested_display_precision": 1,
    },
    # Individual Inverter Energy API additional sensors
    "inverter_power_rating": {
        "name": "Power Rating",
        "unit": None,
        "device_class": None,
        "state_class": None,
        "icon": "mdi:lightning-bolt",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "inverter_lost_status": {
        "name": "Connection Lost",
        "unit": None,
        "device_class": None,
        "state_class": None,
        "icon": "mdi:access-point-network-off",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "off_grid": {
        "name": "Off Grid",
        "unit": None,
        "device_class": None,
        "state_class": None,
        "icon": "mdi:transmission-tower-off",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "inverter_has_runtime_data": {
        "name": "Has Runtime Data",
        "unit": None,
        "device_class": None,
        "state_class": None,
        "icon": "mdi:database-check",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "connection_transport": {
        "name": "Connection Transport",
        "unit": None,
        "device_class": None,
        "state_class": None,
        "icon": "mdi:connection",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    "transport_host": {
        "name": "Transport Address",
        "unit": None,
        "device_class": None,
        "state_class": None,
        "icon": "mdi:connection",
        "entity_category": EntityCategory.DIAGNOSTIC,
    },
    # -------------------------------------------------------------------------
    # Last Polled Diagnostic Sensors (disabled by default)
    # These sensors show when data was last fetched, not when it last changed.
    # Disabled by default because they update every polling cycle and create
    # noisy state history. Users can enable them via the entity registry.
    # -------------------------------------------------------------------------
    "last_polled": {
        "name": "Last Polled",
        "device_class": "timestamp",
        "icon": "mdi:clock-check",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "enabled_default": False,
    },
    "battery_bank_last_polled": {
        "name": "Last Polled",
        "device_class": "timestamp",
        "icon": "mdi:clock-check",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "enabled_default": False,
    },
    "battery_last_polled": {
        "name": "Last Polled",
        "device_class": "timestamp",
        "icon": "mdi:clock-check",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "enabled_default": False,
    },
    "battery_last_seen": {
        "name": "Last Seen",
        "device_class": "timestamp",
        "icon": "mdi:clock-alert-outline",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "enabled_default": False,
    },
    "parallel_group_last_polled": {
        "name": "Last Polled",
        "device_class": "timestamp",
        "icon": "mdi:clock-check",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "enabled_default": False,
    },
    "station_last_polled": {
        "name": "Last Polled",
        "device_class": "timestamp",
        "icon": "mdi:clock-check",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "enabled_default": False,
    },
    "midbox_last_polled": {
        "name": "Last Polled",
        "device_class": "timestamp",
        "icon": "mdi:clock-check",
        "entity_category": EntityCategory.DIAGNOSTIC,
        "enabled_default": False,
    },
}
